# This file should be included "as is" inside a child scope of the main CMakeFiles.txt

# By default we do not use the launcher
SET(INSTALL_EXE OFF PARENT_SCOPE)
SET(SKIP_EXTERNALS_MENSIA_ADVANCED_SIGNAL_PROCESSING_TOOLS ON PARENT_SCOPE)
SET(MENSIA_ADVANCED_SIGNAL_PROCESSING_TOOLS_EXPERIMENTAL OFF)
SET(MENSIA_ADVANCED_VISUALIZATION_EXPERIMENTAL OFF)

# OPENVIBE
SET(SKIP_APPLICATIONS_PLATFORM_DESIGNER ON PARENT_SCOPE)
SET(SKIP_PLUGINS_PROCESSING_SIMPLE-VISUALISATION ON PARENT_SCOPE)
