
GET_PROPERTY(OV_PRINTED GLOBAL PROPERTY OV_TRIED_ThirdPartyMitsar)


IF(WIN32)
	FIND_PATH(PATH_MITSAR MitsarDll.dll)
ENDIF(WIN32)

IF(PATH_MITSAR)
	OV_PRINT(OV_PRINTED "  Found Mitsar dll...")

	INSTALL(PROGRAMS "${PATH_MITSAR}/MitsarDll.dll" DESTINATION ${DIST_BINDIR})
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyMitsar)
ELSE(PATH_MITSAR)
	OV_PRINT(OV_PRINTED "  FAILED to find Mitsar device dll (optional driver). No 64-bits support.")
ENDIF(PATH_MITSAR)

SET_PROPERTY(GLOBAL PROPERTY OV_TRIED_ThirdPartyMitsar "Yes")

