
GET_PROPERTY(OV_PRINTED GLOBAL PROPERTY OV_TRIED_ThirdPartyMCS)


IF(WIN32)
	FIND_PATH(PATH_MCS nvxmcs.dll PATHS PATH_SUFFIXES sdk_mcs/lib)
ENDIF(WIN32)

IF(PATH_MCS)
	OV_PRINT(OV_PRINTED "  Found MCS device SDK...")
	INCLUDE_DIRECTORIES(${PATH_MCS}/../include/)
	TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${PATH_MCS}/nvxmcs.lib)

	INSTALL(PROGRAMS "${PATH_MCS}/nvxmcs.dll" DESTINATION ${DIST_BINDIR})
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyMCS)
ELSE(PATH_MCS)
	OV_PRINT(OV_PRINTED "  FAILED to find MCS device SDK (optional driver). No 64 bits driver")
ENDIF(PATH_MCS)

SET_PROPERTY(GLOBAL PROPERTY OV_TRIED_ThirdPartyMCS "Yes")

