# ---------------------------------
# Finds third party pthread lib
# Adds library to target
# Adds include path
# ---------------------------------

GET_PROPERTY(OV_PRINTED GLOBAL PROPERTY OV_TRIED_ThirdPartyPThread)

IF(WIN32)
	FIND_PATH(PTHREAD_DIR pthread.h)
	FIND_LIBRARY(PTHREAD_LIB pthread.lib)
	FIND_PROGRAM(PTHREAD_DLL pthreadVSE2.dll)

	IF(PTHREAD_LIB AND PTHREAD_DLL)
		OV_PRINT(OV_PRINTED "  Found PThreads")
		INCLUDE_DIRECTORIES(${PTHREAD_DIR}/include)
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${PTHREAD_LIB})
		INSTALL(PROGRAMS "${PTHREAD_DLL}" DESTINATION ${DIST_BINDIR})			
		ADD_DEFINITIONS(-DTARGET_HAS_PThread)
		if (MSVC_VERSION GREATER_EQUAL 1900)
			ADD_DEFINITIONS("-DHAVE_STRUCT_TIMESPEC") # Avoid Pthread to redefine timespec
		endif()
	ELSE()
		OV_PRINT(OV_PRINTED "  FAILED to find PThreads")
	ENDIF()

	IF(PTHREAD_LIB)
		OV_PRINT(OV_PRINTED "    [  OK  ] Third party lib ${PTHREAD_LIB}")
	ELSE()
		OV_PRINT(OV_PRINTED "    [FAILED] Third party lib ${PTHREAD_LIB}")
	ENDIF()
		
ENDIF(WIN32)

IF(UNIX)

	FIND_LIBRARY(LIB_STANDARD_MODULE_PTHREAD pthread)
	IF(LIB_STANDARD_MODULE_PTHREAD)
		OV_PRINT(OV_PRINTED "  Found pthread...")
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_STANDARD_MODULE_PTHREAD})
		ADD_DEFINITIONS(-DTARGET_HAS_PThread)
	ELSE(LIB_STANDARD_MODULE_PTHREAD)
		OV_PRINT(OV_PRINTED "  FAILED to find pthread...")
	ENDIF(LIB_STANDARD_MODULE_PTHREAD)

ENDIF(UNIX)

SET_PROPERTY(GLOBAL PROPERTY OV_TRIED_ThirdPartyPThread "Yes")

