
GET_PROPERTY(OV_PRINTED GLOBAL PROPERTY OV_TRIED_ThirdPartyNeXus)


IF(WIN32)
	FIND_PATH(PATH_NEXUS NeXusDll.dll)
ENDIF(WIN32)

IF(PATH_NEXUS)
	OV_PRINT(OV_PRINTED "  Found MindMedia NeXus dll...")

	INSTALL(PROGRAMS "${PATH_NEXUS}/NeXusDll.dll" "${PATH_NEXUS}/RTInst.dll" DESTINATION ${DIST_BINDIR})
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyNeXus)
ELSE(PATH_NEXUS)
	OV_PRINT(OV_PRINTED "  FAILED to find MindMedia NeXus device dll (optional driver). No 64-bits support.")
ENDIF(PATH_NEXUS)

SET_PROPERTY(GLOBAL PROPERTY OV_TRIED_ThirdPartyNeXus "Yes")

