---

- hosts: all
  vars:
    logname: vagrant

  become: true

  tasks:
    - name: clean WS
      shell: mkdir -p /home/{{ logname }}/openvibe; mkdir -p /home/{{ logname }}/build

    - name:  Clone openvibe 63-add-package-management
      git:
        repo: 'https://gitlab.inria.fr/openvibe/meta.git/'
        single_branch: yes
        version: 63-add-package-management
        dest:  openvibe

    - name: Change openvibe folder owner
      shell: chown -R {{ logname }} /home/{{ logname }}; git config --global --add safe.directory /home/{{ logname }}/openvibe
      
    - name: Download Anaconda
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
#        checksum: 634d76df5e489c44ade4085552b97bebc786d49245ed1a830022b0b406de5817
        mode: 0550
                 
    - name: Check if Anaconda already installer
      ansible.builtin.command: /opt/miniconda3/bin/conda
      register: result
      ignore_errors: true

    - name: Run the installer Anaconda
      ansible.builtin.command: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3
      when: result is failed

    - name: Anaconda already installed
      ansible.builtin.command: echo "miniconda already installed"
      when: result is succeeded
    
    - name: Remove Anaconda the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh
        
    - name: Add path and initialize conda
      shell: export PATH=/opt/miniconda3/bin:$PATH && conda init
      args:
        executable: /bin/bash
        
    - name: Remove previous environment if exist
      shell: /opt/miniconda3/bin/conda env remove -n openvibe

    - name: Install openvibe environment
      shell: /opt/miniconda3/bin/conda env create -n openvibe --file /home/{{ logname }}/openvibe/conda/env_linux.yaml

    - name: activate conda & run & install
      shell: export PATH=/opt/miniconda3/bin:$PATH  && source /opt/miniconda3/bin/activate openvibe && cd /home/{{ logname }}/build; cmake ../openvibe/ && make -j && make install
      args:
        executable: /bin/bash

