#Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu_22.04" do |jammy|
    jammy.vm.box = "ubuntu/jammy64"
    jammy.vm.hostname = 'jammy'
    jammy.vm.box_url = "ubuntu/jammy64"


    jammy.vm.provider "virtualbox" do |v|
        v.memory = 4196
        v.cpus = 2
    end
    jammy.vm.provision "bootstrap_ready", type: "ansible" do |ansible|
      ansible.playbook = "openvibe-22.04.yml"
      ansible.verbose = true
    end
    jammy.ssh.forward_agent = true
    jammy.ssh.forward_x11 = true
    jammy.vm.provision "shell", inline: <<-SHELL
      sudo usermod -aG video vagrant
    SHELL
  end

end
